// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYuv6SaB6VCEyoeA-R0V90wbcvCNWbBY',
    appId: '1:549808844538:web:243d85fa5c4b13b2786343',
    messagingSenderId: '549808844538',
    projectId: 'bets-10c59',
    authDomain: 'bets-10c59.firebaseapp.com',
    storageBucket: 'bets-10c59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc1sTh9tHgGYpItWHMtnRI15Zx0BZstuo',
    appId: '1:549808844538:android:7d28cb4054a73d0b786343',
    messagingSenderId: '549808844538',
    projectId: 'bets-10c59',
    storageBucket: 'bets-10c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Spr4Bl9Th0KHY9NFusyCVhuerBA61hk',
    appId: '1:549808844538:ios:039ed38e50d88871786343',
    messagingSenderId: '549808844538',
    projectId: 'bets-10c59',
    storageBucket: 'bets-10c59.firebasestorage.app',
    iosBundleId: 'com.example.bets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Spr4Bl9Th0KHY9NFusyCVhuerBA61hk',
    appId: '1:549808844538:ios:039ed38e50d88871786343',
    messagingSenderId: '549808844538',
    projectId: 'bets-10c59',
    storageBucket: 'bets-10c59.firebasestorage.app',
    iosBundleId: 'com.example.bets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByYuv6SaB6VCEyoeA-R0V90wbcvCNWbBY',
    appId: '1:549808844538:web:d982fbf2961bc396786343',
    messagingSenderId: '549808844538',
    projectId: 'bets-10c59',
    authDomain: 'bets-10c59.firebaseapp.com',
    storageBucket: 'bets-10c59.firebasestorage.app',
  );
}
